language: python
python:
  - 2.7

sudo: required
dist: trusty

script:
  - python -m py_compile configure_awx.py
  - python -m py_compile delete_awx_templates.py
  - python -m py_compile run_awx_template.py
  
branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7

