language: python
python:
  - 2.7

sudo: required
dist: xenial

install:
  - pip install -r requirements.txt

script:
  - python -m py_compile configure_awx.py
  - python -m py_compile delete_awx_templates.py
  - python -m py_compile run_awx_template.py
  - pylint configure_awx.py -r no
  - pylint delete_awx_templates.py -r no
  - pylint run_awx_template.py -r no
  
branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7

